/* NOTE: This file is generated automatically, to make changes see src/theme/scripts/createNunjucksComponentWrapper */
import '../components/carousel/carousel.js'
import '../components/collage/collage.js'
import '../components/content/content.js'
import '../components/enquiryCatering/enquiryCatering.js'
import '../components/enquiryGroups/enquiryGroups.js'
import '../components/example/example.js'
import '../components/footer/footer.js'
import '../components/form/form.js'
import '../components/header/header.js'
import '../components/logo/logo.js'
import '../components/magicFrame/magicFrame.js'
import '../components/socials/socials.js'
import '../components/ticker/ticker.js'
